### ISSUE TITLE
Request to have all data in HDF5 format

### ISSUE THREAD

**Issue by LeoMcBills** [low-field-mr-image-quality-challenge/low-field-mr-image-quality-challenge.github.io#1]
@sairamgeethanath  Even with the available code to read the [Very low-field (0.05T) MR repeatability data](https://data.mendeley.com/datasets/pysgjrmbnv/1), I initially struggled to set up certain configurations. Now, when I attempt to run demo_read_data.py, I encounter the following error:

```bash

(base) leo@mcbills:~/Music/low-field-mr-image-quality-challenge.github.io/data_read_code$ python3 demo_read_data.py 
QObject::moveToThread: Current thread (0x3f22070) is not the object's thread (0x38efbe0).
Cannot move to target thread (0x3f22070)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/leo/anaconda3/lib/python3.12/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, minimal, minimalegl, offscreen, vnc, webgl.

Aborted (core dumped)
```

It seems the issue is related to the xcb Qt platform plugin, which OpenCV's GUI functionality depends on. I've tried basic troubleshooting, but I still can't resolve the error. Additionally, I recommend storing all data in HDF5 format to ensure uniformity across the project.

Thanks in advance for any insights or assistance!

**Comment by sairamgeethanath** [comment]
Please confirm that you have installed the correct versions in requirements.txt 
I will upload kspace data in h5 if that makes more sense, but that will have to be during the thanksgiving break :)

**Comment by sairamgeethanath** [comment]
Please remove any PyQt from your system. I highly recommend using a virtual environment for use.
Please follow this blogpost [here](https://stackoverflow.com/questions/71088095/opencv-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-fou)

**Comment by LeoMcBills** [comment]
Thanks very much Dr. @sairamgeethanath , I finally solved my problem based on the shared blogpost

**Comment by LeoMcBills** [comment]
I guess I shall close this issue now
